driver:
  name: docker
  use_sudo: false #https://github.com/test-kitchen/kitchen-docker/issues/54
  privileged: true
  publish_all: true
  forward: 22

provisioner:
  name: puppet_apply
  manifests_path: manifests
#  modules_path: modules:/tmp/kitchen/spec/fixtures/modules
#  modules_path: modules:spec/fixtures/modules
#  modules_path: modules:spec/fixtures/modules
#  modules_path: modules
#  hiera_data_path: hieradata
  modules_path: test/fixtures/modules
  #require_chef_for_busser: false
  resolve_with_librarian_puppet: false
  verifier:
    ruby_bindir: '/opt/puppetlabs/bin'


platforms:
  - name: centos-7
    driver_config:
      image: "geoffwilliams/puppet-agent:1.8.2-1_0"
      platform: rhel
      build_context: true
      provision_command:
        - ln -sf /opt/puppetlabs/puppet/bin/puppet /usr/bin/puppet
        - ln -sf /opt/puppetlabs/puppet/bin/facter /usr/bin/facter
        - ln -sf /opt/puppetlabs/puppet/bin/hiera /usr/bin/hiera

suites:
  - name: delete_nis_users
    provisioner:
      manifest: ../modules/system_users/examples/delete_nis_users.pp
#  - name: second_run
#    provisioner:
#      manifest: ../modules/system_users/examples/system_users_disable_overrides.pp
    #provisioner:
  #    puppet_apply_command: |
  #      export MANIFESTDIR='/tmp/kitchen/manifests';
#        sudo -E puppet apply /tmp/kitchen/manifests/../modules/only_before_sync/examples/only_before_sync.pp --modulepath=/tmp/kitchen/modules --fileserverconfig=/tmp/kitchen/fileserver.conf
#        sudo -E puppet apply /tmp/kitchen/manifests/../modules/only_before_sync/examples/only_before_sync_second_run.pp --modulepath=/tmp/kitchen/modules --fileserverconfig=/tmp/kitchen/fileserver.conf

#      custom_install_command: puppet apply /tmp/kitchen/modules/only_before_sync/examples/only_before_sync.pp

#      manifest: ../modules/only_before_sync/examples/only_before_sync_second_run.pp
